<?php

const LANG_RIGHTS_AND_BLOCKS = [
    /* 00 */    'you must be an admin in the chat or have root right',
    /* 01 */    'right value must be 0 or 1',
    /* 02 */    'invalid right or chat',
    /* 03 */    'Right changed successfully',
    /* 04 */    'Chat administrator',
    /* 05 */    'No rights',
    /* 06 */    'Member rights:',
    /* 07 */    '<right> <0/1> <target> [peer_id/chats/pm/every or current chat by default]',
    /* 08 */    'All rights',
    /* 09 */    'List of rights:',
    /* 10 */    'you must have right: %s',
    /* 11 */    'right already registered: %s',
    /* 12 */    'Setting the right value for the member',
    /* 13 */    '<target>',
    /* 14 */    'Learn member rights',
    /* 15 */    'List with names and descriptions of available rights',
    /* 16 */    'Rights management',
    /* 17 */    'Adds rights system',
    /* 18 */    'rights',
    /* 19 */    'set',
    /* 20 */    'info',
    /* 21 */    'list',
    /* 22 */    'you cannot manage external chat rights: %s',
    /* 23 */    'blocks',
    /* 24 */    'Blocks management',
    /* 25 */    '<block> <0/1> <target> [peer_id/chats/pm/every or current chat by default]',
    /* 26 */    'Setting the block value for the member',
    /* 27 */    'Learn member blocks',
    /* 28 */    'List with names and descriptions of available blocks',
    /* 29 */    'Issuing locks',
    /* 30 */    'you cannot manage external chat blocks: %s',
    /* 31 */    'invalid block or chat',
    /* 32 */    'Block changed successfully',
    /* 33 */    'No blocks',
    /* 34 */    'Member blocks:',
    /* 35 */    'List of blocks:',
    /* 36 */    'block already registered: %s',
    /* 37 */    'you have a block: %s',
];